# Generated by Django 6.0.3 on 2026-04-05 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('inc_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora del incidente (por defecto: ahora).')),
                ('incident_type', models.CharField(choices=[('FALLA', 'Falla'), ('SEGURIDAD', 'Seguridad'), ('OPERACION', 'Operación'), ('OTRO', 'Otro')], db_index=True, default='OTRO', help_text='Clasificación del incidente.', max_length=20)),
                ('description', models.TextField(help_text='Descripción detallada del incidente.')),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', help_text='Estado del incidente.', max_length=20)),
                ('responsible', models.CharField(db_index=True, help_text='Persona responsable o asignada.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Permite desactivar el registro sin eliminarlo (borrado lógico).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación (automática).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación (automática).')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-date', '-inc_id'],
                'constraints': [models.UniqueConstraint(fields=('date', 'incident_type', 'responsible'), name='uq_incident_date_type_responsible')],
            },
        ),
    ]
